@startuml

title Components - Component Diagram


  
  node "Device" {
  [Client]
  }

   node "Server" {
  [DataBase]
  [Server App]
  }
  
 node "OS Process" {
  [Main App]
  }
  
  [Client] --> [Main App] : request

  [Main App] --> [Client] : respone

  [Main App] --> [Server App] : request

  [Server App] --> [Main App] : respone

  [DataBase] --> [Server App] : respone

  [Server App] --> [DataBase] : request

@enduml